export const REGISTER_USER = 'REGISTER_USER'
export const RECIEVED_REGISTER_USER = 'RECIEVED_REGISTER_USER'
export const FAILURE_REGISTER_USER = 'FAILURE_REGISTER_USER'

export const LOGIN_USER = 'LOGIN_USER'
export const RECIEVED_LOGIN_USER = 'RECIEVED_LOGIN_USER'
export const FAILURE_LOGIN_USER = 'FAILURE_LOGIN_USER'

export const GET_USER_CASES = 'GET_USER_CASES'
export const RECIEVED_GET_USER_CASES = 'RECIEVED_GET_USER_CASES'
export const FAILURE_GET_USER_CASES = 'FAILURE_GET_USER_CASES'

export const PAYMENT = 'PAYMENT'
export const RECIEVED_PAYMENT = 'RECIEVED_PAYMENT'
export const FAILURE_PAYMENT = 'FAILURE_PAYMENT'

export const GET_CASE = 'GET_CASE'
export const RECIEVED_GET_CASE = 'RECIEVED_GET_CASE'
export const FAILURE_GET_CASE = 'FAILURE_GET_CASE'

export const CREATE_CASE = 'CREATE_CASE'
export const RECIEVED_CREATE_CASE = 'RECIEVED_CREATE_CASE'
export const FAILURE_CREATE_CASE = 'FAILURE_CREATE_CASE'

export const UPLOAD_CASE_IMAGE = 'UPLOAD_CASE_IMAGE'
export const RECIEVED_UPLOAD_CASE_IMAGE = 'RECIEVED_UPLOAD_CASE_IMAGE'
export const FAILURE_UPLOAD_CASE_IMAGE = 'FAILURE_UPLOAD_CASE_IMAGE'

export const GET_CASE_IMAGE = 'GET_CASE_IMAGE'
export const RECIEVED_GET_CASE_IMAGE = 'RECIEVED_GET_CASE_IMAGE'
export const FAILURE_GET_CASE_IMAGE = 'FAILURE_GET_CASE_IMAGE'

export const CALIBRATE = 'CALIBRATE'
export const RECIEVED_CALIBRATEE = 'RECIEVED_CALIBRATEE'
export const FAILURE_CALIBRATE = 'FAILURE_CALIBRATE'

export const GET_ALL_ANALYZE_TYPES = 'GET_ALL_ANALYZE_TYPES'
export const RECIEVED_GET_ALL_ANALYZE_TYPES = 'RECIEVED_GET_ALL_ANALYZE_TYPES'
export const FAILURE_GET_ALL_ANALYZE_TYPESE = 'FAILURE_GET_ALL_ANALYZE_TYPESE'

export const GET_TRG_POINTS_AI = 'GET_TRG_POINTS_AI'
export const RECIEVED_GET_TRG_POINTS_AI = 'RECIEVED_GET_TRG_POINTS_AI'
export const FAILURE_GET_TRG_POINTS_AI = 'FAILURE_GET_TRG_POINTS_AI'

export const GET_ALL_POINTS = 'GET_ALL_POINTS'
export const RECIEVED_GET_ALL_POINTS = 'RECIEVED_GET_ALL_POINTS'
export const FAILURE_GET_ALL_POINTS = 'FAILURE_GET_ALL_POINTS'

export const GET_DELINEATION_IMG = 'GET_DELINEATION_IMG'
export const RECIEVED_GET_DELINEATION_IMG = 'RECIEVED_GET_DELINEATION_IMG'
export const FAILURE_GET_DELINEATION_IMG = 'FAILURE_GET_DELINEATION_IMG'

export const UPDATE_CASE = 'UPDATE_CASE'
export const RECIEVED_UPDATE_CASE = 'RECIEVED_UPDATE_CASE'
export const FAILURE_UPDATE_CASE= 'FAILURE_UPDATE_CASE'

export const GET_ALL_MEASURMENTS = 'GET_ALL_MEASURMENTS'
export const RECIEVED_GET_ALL_MEASURMENTS = 'RECIEVED_GET_ALL_MEASURMENTS'
export const FAILURE_GET_ALL_MEASURMENTSE= 'FAILURE_GET_ALL_MEASURMENTSE'

export const GET_REPORT = 'GET_REPORT'
export const RECIEVED_GET_REPORT = 'RECIEVED_GET_REPORT'
export const FAILURE_GET_REPORT= 'FAILURE_GET_REPORT'

export const GET_POINT_INFO = 'GET_POINT_INFO'
export const RECIEVED_GET_POINT_INFO = 'RECIEVED_GET_POINT_INFO'
export const FAILURE_GET_POINT_INFO= 'FAILURE_GET_POINT_INFO'

export const DELETE_CASE = 'DELETE_CASE'
export const RECIEVED_DELETE_CASE = 'RECIEVED_DELETE_CASE'
export const FAILURE_DELETE_CASE = 'FAILURE_DELETE_CASE'